--0306231010
--Trần Hồ Khánh Duy 
--CD TH 23A

CREATE DATABASE QuanLyDuAn
GO
USE QuanLyDuAn;
GO
--Câu 1
-- Tạo bảng Đề Án
create table DEAN
(
	TENDA nvarchar(15),
	MADA int,
	DDIEM_DA nvarchar(15),
	PHONG int,
)

-- Tạo bảng Công Việc
create table CONGVIEC
(
	MADA int,
	STT int,
	TEN_CONG_VIEC nvarchar(50),
)

-- Tạo bảng Phòng Ban
create table PHONGBAN
(
	TENPHG nvarchar(15),
	MAPHG int,
	TRPHG char(9),
	NG_NHANCHUC date,
)

-- Tạo bảng Phân Công
create table PHANCONG
(
	MA_NVIEN  char(9),
	MADA int,
	STT int,
	THOIGIAN float,
)

-- Tạo bảng Thân Nhân
create table THANNHAN
(
	MA_NVIEN char(9),
	TENTN nvarchar(15),
	PHAI nvarchar(3),
	NGSINH date,
	QUANHE  nvarchar(15),
)

-- Tạo bảng Địa Điểm Phòng
create table DIADIEM_PHG
(
	MAPHG  int,
	DIADIEM nvarchar(15),
)
--Tạo bảng Nhân Viên
create table NHANVIEN
(
	HONV NVARCHAR(20),
	TENLOT NVARCHAR(20),
	TENNV NVARCHAR(20),
	MANV CHAR(9) NOT NULL,
	NGSINH DATE,
	DCHI NVARCHAR(20),
	PHAI NVARCHAR(3),
	LUONG MONEY,
	MA_NQL CHAR(9),
	PHG INT
)
--Câu 2
ALTER TABLE NHANVIEN
ADD CONSTRAINT PR_NHANVIEN PRIMARY KEY(MANV)

ALTER TABLE DIADIEM_PHG
ALTER COLUMN MAPHG INT NOT NULL
ALTER TABLE DIADIEM_PHG
ADD CONSTRAINT PR_DIADIEM_PHG PRIMARY KEY(MAPHG)


ALTER TABLE PHANCONG
ALTER COLUMN MA_NVIEN CHAR(9) NOT NULL

ALTER TABLE PHANCONG
ALTER COLUMN MADA INT NOT NULL

ALTER TABLE PHANCONG
ALTER COLUMN STT INT NOT NULL

ALTER TABLE PHANCONG
ADD CONSTRAINT PR_PHANCONG PRIMARY KEY(MA_NVIEN,MADA,STT)

ALTER TABLE THANNHAN
ALTER COLUMN MA_NVIEN CHAR(9) NOT NULL

ALTER TABLE THANNHAN
ALTER COLUMN TENTN NVARCHAR(15) NOT NULL


ALTER TABLE THANNHAN
ADD CONSTRAINT PR_THANHAN PRIMARY KEY(MA_NVIEN,TENTN)


ALTER TABLE CONGVIEC
ALTER COLUMN MADA INT NOT NULL

ALTER TABLE CONGVIEC
ALTER COLUMN STT INT NOT NULL

ALTER TABLE CONGVIEC
ADD CONSTRAINT PR_CONGVIEC PRIMARY KEY(MADA,STT)

ALTER TABLE DEAN
ALTER COLUMN MADA INT NOT NULL

ALTER TABLE DEAN
ADD CONSTRAINT PR_DEAN PRIMARY KEY(MADA)


ALTER TABLE PHONGBAN
ALTER COLUMN MAPHG INT NOT NULL

ALTER TABLE PHONGBAN
ADD CONSTRAINT PR_PHONGBAN PRIMARY KEY(MAPHG)

ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN_PHONGBAN FOREIGN KEY(PHG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE PHONGBAN 
ADD CONSTRAINT PK_PHONGBAN_NHANVIEN FOREIGN KEY(TRPHG) REFERENCES NHANVIEN(MANV)


ALTER TABLE DIADIEM_PHG
ADD CONSTRAINT PK_DIADIEM_PHG_PHONGBAN FOREIGN KEY(MAPHG) REFERENCES PHONGBAN(MAPHG)


ALTER TABLE DEAN
ADD CONSTRAINT PK_DEAN_PHONGBAN FOREIGN KEY(PHONG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE PHANCONG
ADD CONSTRAINT PK_PHANCONG_DEAN FOREIGN KEY (MADA) REFERENCES DEAN(MADA)

ALTER TABLE CONGVIEC
ADD CONSTRAINT PK_CONGVIEC_DEAN FOREIGN KEY (MADA) REFERENCES DEAN(MADA)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV)

ALTER TABLE THANNHAN
ADD CONSTRAINT FK_THANNHAN_NHANVIEN FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_NHANVIEN FOREIGN KEY (MA_NQL) REFERENCES NHANVIEN(MANV)
 ALTER TABLE NHANVIEN
 ALTER COLUMN DCHI NVARCHAR(50)

 --Câu 4

INSERT INTO NHANVIEN(HONV,
	TENLOT,
	TENNV ,
	MANV ,
	NGSINH ,
	DCHI ,
	PHAI ,
	LUONG ,
	MA_NQL, 
	PHG )
VALUES (N'NGUYỄN', N'THANH',N'TRÚC','004','1/1/2000',N'200 CỐNG QUỲNH Q1 TP HCM',N'NỮ',10000,NULL,NULL)
INSERT INTO NHANVIEN(HONV,
	TENLOT,
	TENNV ,
	MANV ,
	NGSINH ,
	DCHI ,
	PHAI ,
	LUONG ,
	MA_NQL, 
	PHG )
VALUES (N'NGUYỄN', N'THANH',N'LOAN','005','1/1/2000',N'200 CỐNG QUỲNH Q1 TP HCM',N'NỮ',10000,NULL,NULL)


INSERT INTO NHANVIEN(HONV,
	TENLOT,
	TENNV ,
	MANV ,
	NGSINH ,
	DCHI ,
	PHAI ,
	LUONG ,
	MA_NQL, 
	PHG )
VALUES (N'NGUYỄN', NULL,N'LINH','006','1/1/2000',N'200 CỐNG QUỲNH Q1 TP HCM',N'NỮ',10000,NULL,NULL)
--Câu 5
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_NHANVIEN_PHAI CHECK(PHAI LIKE N'NAM' OR PHAI LIKE N'NỮ')
INSERT INTO NHANVIEN(HONV,
	TENLOT,
	TENNV ,
	MANV ,
	NGSINH ,
	DCHI ,
	PHAI ,
	LUONG ,
	MA_NQL, 
	PHG )
VALUES (N'NGUYỄN', NULL,N'LINH','007','1/1/2000',N'200 CỐNG QUỲNH Q1 TP HCM',N'NAM',10000,NULL,NULL)
--Câu 6
ALTER TABLE DEAN
ADD CONSTRAINT PK_DEAN PRIMARY KEY (MADA);

ALTER TABLE DEAN
ADD CONSTRAINT UQ_DEAN_TENDA UNIQUE (TENDA);

INSERT INTO DEAN
VALUES(N'Học HQT',1,N'Hà Nội', null)

INSERT INTO DEAN
VALUES(N'Học HQT',2,N'Hải Phòng', null)
--Câu 7
ALTER TABLE NHANVIEN
ADD NGAYVAOLAM DATE DEFAULT GETDATE();
--không có giá trị ngayvaolam
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES (N'LE', N'VAN', N'NAM', '008', '1999-05-05', N'100 ĐIỆN BIÊN PHỦ', N'NAM', 12000, NULL, NULL);
--có giá trị ngayvaolam
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG, NGAYVAOLAM)
VALUES (N'LE', N'THI', N'TRANG', '009', '1998-12-12', N'300 BẠCH ĐẰNG', N'NỮ', 15000, NULL, NULL, '2023-09-01');

SELECT * 
FROM NHANVIEN 
WHERE MANV IN ('008', '009');
--Câu 8
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_NHANVIEN_NGAYSINH_NGAYVAOLAM CHECK (NGSINH < NGAYVAOLAM)
--du lieu hop le NHANVIEN
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG, NGAYVAOLAM)
VALUES (N'TRẦN', N'VĂN', N'HẢI', '010', '1995-06-10', N'123 LÝ TỰ TRỌNG', N'NAM', 20000, NULL, NULL, '2020-01-01')
--khong hop le
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG, NGAYVAOLAM)
VALUES (N'NGUYỄN', N'THỊ', N'BÍCH', '011', '2021-06-10', N'456 NGUYỄN HUỆ', N'NỮ', 18000, NULL, NULL, '2020-01-01')
--Câu 9
CREATE RULE GiaTri0 AS @value > 0;
EXEC sp_bindrule 'Rule_GT0', 'PHONGBAN.MAPHG';
--Câu 10
CREATE RULE TUOITU18 AS @value >= 18
AS YEAR(GETDATE()-@ngay)-1900>=18  --ngsinh datetime
EXEC sp_bindrule 'TUOITU18','NHANVIEN.NGSINH'
--Câu 11
EXEC sp_unbindrule 'PHONGBAN.MAPHG';
DROP RULE Rule_GT0;
--Câu 12
DROP RULE Rule_GT0;