--0306231010
--Trần Hồ Khánh Duy
--CD TH 23A

CREATE DATABASE QUANLYBANHANG
GO 
USE QUANLYBANHANG
GO

CREATE TABLE KHACHHANG
(
	MAKH CHAR(10),
	HOTEN	NVARCHAR(25),
	DCHI	NVARCHAR(25),
	SODT	NUMERIC(10),
	NGSINH	DATETIME,
	DOANHSO	NVARCHAR(25),
	NGDK	DATE,
)	

CREATE TABLE NHANVIEN
(
	MANV	CHAR(9),
	HOTEN	NVARCHAR(25),
	NGVL	DATETIME,
	SODT	NUMERIC(10),
)

CREATE TABLE SANPHAM
(
	MASP	CHAR(6),
	TENSP	NVARCHAR(25),
	DVT		NVARCHAR(25),
	NUOCSX	NVARCHAR(25),
	GIA		MONEY,
)

CREATE TABLE HOADON
(
	SOHD	INT,
	NGHD	DATETIME,
	MAKH	CHAR(6),
	MANV	CHAR(10),
	TRIGIA	MONEY,
)
CREATE TABLE  CTHD
(
	SOHD	INT,
	MASP	CHAR(6),
	SL		INT,
)

--Câu 1
ALTER TABLE KHACHHANG
ALTER COLUMN MAKH CHAR(10)  NOT NULL
ALTER TABLE KHACHHANG
ADD CONSTRAINT PR_KHACHHANG
PRIMARY KEY (MAKH)

ALTER TABLE NHANVIEN
ALTER COLUMN MANV CHAR(9) NOT NULL
ALTER TABLE NHANVIEN
ADD CONSTRAINT	PR_NHANVIEN
PRIMARY KEY (MANV)

ALTER TABLE SANPHAM
ALTER COLUMN MASP CHAR(6) NOT NULL
ALTER TABLE SANPHAM
ADD CONSTRAINT PR_SANPHAM
PRIMARY KEY (MASP)

ALTER TABLE HOADON
ALTER COLUMN SOHD INT NOT NULL

ALTER TABLE HOADON
ADD CONSTRAINT PR_HOADON
PRIMARY KEY (SOHD)

ALTER TABLE HOADON ADD  CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE HOADON ADD CONSTRAINT FK_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CTHD
ALTER COLUMN SOHD INT NOT NULL
ALTER TABLE CTHD 
ALTER COLUMN MASP CHAR(6) NOT NULL
ALTER TABLE CTHD
ADD CONSTRAINT PR_CTHD
PRIMARY KEY ( SOHD,MASP)

ALTER TABLE CTHD ADD CONSTRAINT FK_SOHD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)
ALTER TABLE CTHD ADD CONSTRAINT FK_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

--Câu 2
ALTER TABLE SANPHAM
ADD	GHICHU VARCHAR(20)

--Câu 3
ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT

--Câu 4
ALTER TABLE SANPHAM 
ALTER COLUMN GHICHU VARCHAR(100)

--Câu 6
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_KHACHHANG_LOAIKH CHECK(LOAIKH IN('Vang lai', 'Thuong xuyen', 'Vip'))

--Câu 7
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SANPHAM_DVT CHECK(DVT IN('cay', 'hop', 'cai', 'quyen', 'chuc'))

--Câu 8
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SANPHAM_GIA CHECK (GIA>=500)

--Câu 9
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_NGAYSINH_NGDK CHECK(NGDK>NGSINH)

--Câu 10
ALTER TABLE HOADON 
ADD CONSTRAINT CK_NGHD_NGDK 
CHECK (NGHD >= (SELECT NGDK 
FROM KHACHHANG 
WHERE KHACHHANG.MAKH = HOADON.MAKH))

--Câu 11
ALTER TABLE HOADON 
ADD CONSTRAINT CK_NGHD_NVL
CHECK (NGHD >= (SELECT NGVL 
FROM NHANVIEN 
WHERE NHANVIEN.MANV = HOADON.MANV))


